// Palmarés del 79º Festival de Cannes (mayo 2026).
// Título, director y premio van fijos aquí porque TMDB a veces no los tiene en español
// (ej. regresa el título en japonés o el director en cirílico). De TMDB solo tomamos póster, año y sinopsis.
export const cannes2026 = [
  {
    tmdbId: 1401459,
    premio: "Palma de Oro",
    titulo: "Fjord",
    tituloAlt: null,
    director: "Cristian Mungiu",
  },
  {
    tmdbId: 848700,
    premio: "Gran Premio",
    titulo: "Minotaure",
    tituloAlt: "Minotaur",
    director: "Andréi Zviáguintsev",
  },
  {
    tmdbId: 1013822,
    premio: "Premio del Jurado",
    titulo: "Das geträumte Abenteuer",
    tituloAlt: "The Dreamed Adventure",
    director: "Valeska Grisebach",
  },
  {
    tmdbId: 1422041,
    premio: "Mejor Dirección",
    titulo: "La bola negra",
    tituloAlt: null,
    director: "Javier Ambrossi y Javier Calvo",
  },
  {
    tmdbId: 1437696,
    premio: "Mejor Dirección",
    titulo: "Tierra de mi padre",
    tituloAlt: "Fatherland",
    director: "Paweł Pawlikowski",
  },
  {
    tmdbId: 1476614,
    premio: "Mejor Actriz",
    titulo: "Soudain",
    tituloAlt: "All of a Sudden",
    director: "Ryûsuke Hamaguchi",
    nota: "Virginie Efira y Tao Okamoto",
  },
  {
    tmdbId: 1437981,
    premio: "Mejor Actor",
    titulo: "Cobarde",
    tituloAlt: "Coward",
    director: "Lukas Dhont",
    nota: "Emmanuel Macchia y Valentin Campagne",
  },
  {
    tmdbId: 1318864,
    premio: "Mejor Guion",
    titulo: "Notre salut",
    tituloAlt: "A Man of His Time",
    director: "Emmanuel Marre",
  },
  {
    tmdbId: 1405200,
    premio: "Cámara de Oro",
    titulo: "Ben'Imana",
    tituloAlt: null,
    director: "Marie-Clémentine Dusabejambo",
  },
  {
    tmdbId: 1655419,
    premio: "Premio Un Certain Regard",
    titulo: "Everytime",
    tituloAlt: null,
    director: "Sandra Wollner",
  },
];

// Fuera del palmarés oficial, pero de lo mejor recibido por la crítica en el festival.
export const cannes2026Recomendadas = [
  {
    tmdbId: 1154730,
    seccion: "Semana de la Crítica",
    titulo: "La Gradiva",
    tituloAlt: null,
    director: "Marine Atlan",
    nota: "Gran Premio de la Semana de la Crítica",
  },
  {
    tmdbId: 1240889,
    seccion: "Queer Palm",
    titulo: "Adolescencia, sexo y muerte en Campamento Miasma",
    tituloAlt: "Teenage Sex and Death at Camp Miasma",
    director: "Jane Schoenbrun",
  },
  {
    tmdbId: 1058424,
    seccion: "Competencia oficial",
    titulo: "Hope",
    tituloAlt: "호프",
    director: "Na Hong-jin",
  },
  {
    tmdbId: 1381273,
    seccion: "Competencia oficial",
    titulo: "Tigre de papel",
    tituloAlt: "Paper Tiger",
    director: "James Gray",
  },
  {
    tmdbId: 1074074,
    seccion: "Competencia oficial",
    titulo: "El ser querido",
    tituloAlt: "The Beloved",
    director: "Rodrigo Sorogoyen",
  },
  {
    tmdbId: 1620313,
    seccion: "Competencia oficial",
    titulo: "The Samurai and the Prisoner",
    tituloAlt: "黒牢城",
    director: "Kiyoshi Kurosawa",
  },
  {
    tmdbId: 1585239,
    seccion: "Competencia oficial",
    titulo: "Club Kid",
    tituloAlt: null,
    director: "Jordan Firstman",
  },
  {
    tmdbId: 1458914,
    seccion: "Competencia oficial",
    titulo: "The Man I Love",
    tituloAlt: null,
    director: "Ira Sachs",
  },
  {
    tmdbId: 1182935,
    seccion: null,
    titulo: "L'Inconnue",
    tituloAlt: "The Unknown",
    director: "Arthur Harari",
  },
  {
    tmdbId: 1448971,
    seccion: "Competencia oficial",
    titulo: "Nagi Notes",
    tituloAlt: "ナギダイアリー",
    director: "Kôji Fukada",
  },
  {
    tmdbId: 1630464,
    seccion: "Quincena de Cineastas",
    titulo: "Clarissa",
    tituloAlt: null,
    director: "Arie Esiri y Chuko Esiri",
  },
  {
    tmdbId: 1472813,
    seccion: "Quincena de Cineastas",
    titulo: "Le Journal d'une femme de chambre",
    tituloAlt: "The Diary of a Chambermaid",
    director: "Radu Jude",
  },
];
