// Palmarés de la 83ª Mostra de Venecia (septiembre 2026).
// Igual que en Cannes: título, director y premio van fijos aquí; de TMDB solo tomamos póster, año y sinopsis.
export const venecia2026 = [
  {
    tmdbId: 1511780,
    premio: "León de Oro",
    titulo: "Woman Unknown",
    tituloAlt: "Kvinde ukendt",
    director: "May el-Toukhy",
    nota: "También Copa Volpi a Mejor Actriz (Mathilde Arcel)",
  },
  {
    tmdbId: 1483525,
    premio: "Gran Premio del Jurado",
    titulo: "Possible Love",
    tituloAlt: "가능한 사랑",
    director: "Lee Chang-dong",
  },
  {
    tmdbId: 1734147,
    premio: "Mejor Dirección",
    titulo: "DAU",
    tituloAlt: null,
    director: "Ilya Khrzhanovsky",
  },
  {
    tmdbId: 1755291,
    premio: "Premio Especial del Jurado",
    titulo: "NAZA",
    tituloAlt: null,
    director: "Yuval Abraham y Rachel Szor",
  },
  {
    tmdbId: 1430815,
    premio: "Mejor Guion",
    titulo: "Un bon petit soldat",
    tituloAlt: "A Good Little Soldier",
    director: "Stéphane Brizé",
  },
  {
    tmdbId: 891621,
    premio: "Copa Volpi Mejor Actor",
    titulo: "Caballo salvaje nueve",
    tituloAlt: "Wild Horse Nine",
    director: "Martin McDonagh",
    nota: "John Malkovich",
  },
  {
    tmdbId: 1429602,
    premio: "Premio Marcello Mastroianni",
    titulo: "15/18",
    tituloAlt: "A Place to Heal",
    director: "Cédric Kahn",
    nota: "Malou Khebizi, mejor actriz o actor joven",
  },
  {
    tmdbId: 1404592,
    premio: "León del Futuro",
    titulo: "La Maison du vent",
    tituloAlt: "House of the Wind",
    director: "Auguste Bernard Kouemo Yanghu",
    nota: "Mejor ópera prima y Premio Especial del Jurado en Orizzonti",
  },
  {
    tmdbId: 1404588,
    premio: "Mejor Película Orizzonti",
    titulo: "Un détour par Diane",
    tituloAlt: "Diane in the Loop",
    director: "Ann Sirot y Raphaël Balboni",
  },
  {
    tmdbId: 1510542,
    premio: "Mejor Dirección Orizzonti",
    titulo: "A Day in the Life of Jo: Chapter Phaedra",
    tituloAlt: "Mia mera sti zoi tis Tzo: Kefalaio Faidra",
    director: "Jacqueline Lentzou",
  },
];

// Fuera del palmarés oficial, pero de lo mejor recibido por la crítica en el festival.
export const venecia2026Recomendadas = [
  {
    tmdbId: 1591675,
    seccion: "Competencia oficial",
    titulo: "Look Back",
    tituloAlt: "ルックバック",
    director: "Hirokazu Kore-eda",
  },
  {
    tmdbId: 1375441,
    seccion: "Competencia oficial",
    titulo: "Primetime",
    tituloAlt: null,
    director: "Lance Oppenheim",
  },
  {
    tmdbId: 1532610,
    seccion: "Competencia oficial",
    titulo: "Ink",
    tituloAlt: null,
    director: "Danny Boyle",
  },
  {
    tmdbId: 1497946,
    seccion: "Competencia oficial",
    titulo: "Mr. Nelson, Did You Kill People?",
    tituloAlt: "ネルソンさん、あなたは人を殺しましたか？",
    director: "Shinya Tsukamoto",
  },
  {
    tmdbId: 1412795,
    seccion: "Competencia oficial",
    titulo: "L'estranea",
    tituloAlt: "The Spiral",
    director: "Paolo Strippoli",
  },
  {
    tmdbId: 1429713,
    seccion: "Competencia oficial",
    titulo: "Bucking Fastard",
    tituloAlt: null,
    director: "Werner Herzog",
  },
  {
    tmdbId: 1736516,
    seccion: "Queer Lion",
    titulo: "Queer Edward II",
    tituloAlt: null,
    director: "Theo Rollason",
  },
  {
    tmdbId: 1484090,
    seccion: "Venice Spotlight",
    titulo: "Furies",
    tituloAlt: null,
    director: "Rami Kodeih",
  },
  {
    tmdbId: 1736499,
    seccion: "Orizzonti",
    titulo: "Too Much Sugar",
    tituloAlt: null,
    director: "Robert Greene",
  },
  {
    tmdbId: 1594307,
    seccion: "Fuera de competencia",
    titulo: "My Undesirable Friends: Part II – Exile",
    tituloAlt: null,
    director: "Julia Loktev",
  },
  {
    tmdbId: 1447853,
    seccion: "Fuera de competencia",
    titulo: "Oasis: Don't Look Back in Anger",
    tituloAlt: null,
    director: "Dylan Southern y Will Lovelace",
  },
];
