export const Subtitles = () => {
  const sutitlesObject = [
    {
      tmdb_ID: "10843",
      name: "despues-de-hora",
      videoSrc: "https://mcseguros.com.mx/cineclub/after-hours.mp4",
      subtitlePath: "/subtitles/after-hours-subs-esp.vtt",
      ciclo: "Snob",
      propuestaPor: "Payin",
    },
    {
      tmdb_ID: "4723",
      name: "las-horas-perdidas",
      videoSrc: "https://mcseguros.com.mx/cineclub/las-horas-perdidas.mp4",
      subtitlePath: "/subtitles/las-horas-perdidas-subs-esp.vtt",
      ciclo: "Snob",
      propuestaPor: "Wally",
    },
    {
      tmdb_ID: "21484",
      name: "posesion",
      videoSrc: "https://mcseguros.com.mx/cineclub/possession.mp4",
      subtitlePath: "/subtitles/possession-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Luis",
      customPoster: "/lUFZsUuJ0YyhBXH8D2BFUd6wODm.jpg",
    },
    {
      tmdb_ID: "883083",
      name: "no-estaras-sola",
      videoSrc: "https://mcseguros.com.mx/cineclub/you-wont-be-alone.mp4",
      subtitlePath: "/subtitles/no-estaras-sola-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Luis",
    },
    {
      tmdb_ID: "524635",
      name: "the-chronology-of-water",
      videoSrc: "https://mcseguros.com.mx/cineclub/cronologia-del-agua.mp4",
      subtitlePath: "/subtitles/cronologia-del-agua-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Luis",
    },
    {
      tmdb_ID: "1242011",
      name: "together-juntos-hasta-la-muerte",
      videoSrc: "https://mcseguros.com.mx/cineclub/together.mp4",
      subtitlePath: "/subtitles/together-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Luis",
    },
    {
      tmdb_ID: "1287141",
      name: "pillion",
      videoSrc: "https://mcseguros.com.mx/cineclub/pasajero.mp4",
      subtitlePath: "/subtitles/pasajero-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Alma",
    },
    {
      tmdb_ID: "1325734",
      name: "el-drama",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-drama.mp4",
      subtitlePath: "/subtitles/the-drama-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Luis",
    },
    {
      tmdb_ID: "13222",
      name: "the-devil-and-daniel-johnston",
      videoSrc: "https://mcseguros.com.mx/cineclub/devil.mp4",
      subtitlePath: "/subtitles/devil-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "ConejoNegro",
    },
    {
      tmdb_ID: "1160360",
      name: "si-pudiera-te-daria-una-patada",
      videoSrc: "https://mcseguros.com.mx/cineclub/legs.mp4",
      subtitlePath: "/subtitles/legs-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Mariana M",
    },
    {
      tmdb_ID: "1151272",
      name: "sirat-trance-en-el-desierto",
      videoSrc: "https://mcseguros.com.mx/cineclub/sirat.mp4",
      subtitlePath: "/subtitles/sirat-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Ian",
    },
    {
      tmdb_ID: "1245993",
      name: "atrapado-robando",
      videoSrc: "https://mcseguros.com.mx/cineclub/atrapado-robando.mp4",
      subtitlePath: "/subtitles/atrapado-robando-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Cone",
    },
    {
      tmdb_ID: "970947",
      name: "the-shrouds",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-shrouds.mp4",
      subtitlePath: "/subtitles/spanish-the-shrouds.vtt",
      ciclo: "Libre",
      propuestaPor: "Cone",
    },
    {
      tmdb_ID: "474444",
      name: "les-garcons-sauvages",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-wild-boys.mp4",
      subtitlePath: "/subtitles/the-wild-boys-esp.vtt",
      ciclo: "Teens",
      propuestaPor: "Mingo Morales",
    },
  ];

  return sutitlesObject;
};
