export const Subtitles = () => {  
  const sutitlesObject = [ 
    {
      tmdb_ID: "277216",
      name: "letras-explicitas-straight-outta-compton",
      videoSrc: "https://mcseguros.com.mx/cineclub/compton.mp4",
      subtitlePath: "/subtitles/compton-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "Eric",
    },
    {
      tmdb_ID: "13222",
      name: "the-devil-and-daniel-johnston",
      videoSrc: "https://mcseguros.com.mx/cineclub/devil.mp4",
      subtitlePath: "/subtitles/devil-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "ConejoNegro",
    },
    {
      tmdb_ID: "426249",
      name: "lords-of-chaos",
      videoSrc: "https://mcseguros.com.mx/cineclub/lords-of-chaos.mp4",
      subtitlePath: "/subtitles/lords-of-chaos-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "Jorge",
    },
    {
      tmdb_ID: "1317288",
      name: "marty-supremo",
      videoSrc: "https://mcseguros.com.mx/cineclub/marty.mp4",
      subtitlePath: "/subtitles/marty-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "ConejoNegro",
    },
    {
      tmdb_ID: "1160360",
      name: "si-pudiera-te-daria-una-patada",
      videoSrc: "https://mcseguros.com.mx/cineclub/legs.mp4",
      subtitlePath: "/subtitles/legs-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Mariana M",
    },
    {
      tmdb_ID: "1151272",
      name: "sirat-trance-en-el-desierto",
      videoSrc: "https://mcseguros.com.mx/cineclub/sirat.mp4",
      subtitlePath: "/subtitles/sirat-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Ian",
    },
    {
      tmdb_ID: "639988",
      name: "la-unica-opcion",
      videoSrc: "https://mcseguros.com.mx/cineclub/no-other-choice.mp4",
      subtitlePath: "/subtitles/no-other-choice-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "ConejoNegro",
    },
    {
      tmdb_ID: "701387",
      name: "bugonia",
      videoSrc: "https://mcseguros.com.mx/cineclub/bugonia.mp4",
      subtitlePath: "/subtitles/bugonia-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "ConejoNegro",
    },
    {
      tmdb_ID: "9538",
      name: "telepatas-mentes-destructoras",
      videoSrc: "https://mcseguros.com.mx/cineclub/scanners.mp4",
      subtitlePath: "/subtitles/scanners-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "Cone",
    },
    {
      tmdb_ID: "4995",
      name: "boogie-nights-juegos-de-placer",
      videoSrc: "https://mcseguros.com.mx/cineclub/boogie-nights.mp4",
      subtitlePath: "/subtitles/boogie-nights-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "Cone",
    },
    {
      tmdb_ID: "2654",
      name: "en-la-boca-del-miedo",
      videoSrc: "https://mcseguros.com.mx/cineclub/en-la-boca-del-miedo.mp4",
      subtitlePath: "/subtitles/en-la-boca-del-miedo-subs-esp.vtt",
      ciclo:"Halloween",
      propuestaPor: "Alfred",
    },
    {
      tmdb_ID: "1245993",
      name: "atrapado-robando",
      videoSrc: "https://mcseguros.com.mx/cineclub/atrapado-robando.mp4",
      subtitlePath: "/subtitles/atrapado-robando-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "Cone",
    },
    {
      tmdb_ID: "510",
      name: "atrapado-sin-salida",
      videoSrc: "https://mcseguros.com.mx/cineclub/cukoos-nest.mp4",
      subtitlePath: "/subtitles/cuckos-nest-subs-esp.vtt",
      ciclo:"Libre",
      propuestaPor: "Mariana Nunez",
    },
    {
      tmdb_ID: "970947",
      name: "the-shrouds",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-shrouds.mp4",
      subtitlePath: "/subtitles/spanish-the-shrouds.vtt",
      ciclo:"Libre",
      propuestaPor: "Cone",
    },
    {
      tmdb_ID: "1050035",
      name: "monstruo",
      videoSrc: "https://mcseguros.com.mx/cineclub/monster.mp4",
      subtitlePath: "/subtitles/monster.vtt",
      ciclo: "Orgullo Gay",
      propuestaPor: "Mingo Morales",
    },
    {
      tmdb_ID: "474444",
      name: "les-garcons-sauvages",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-wild-boys.mp4",
      subtitlePath: "/subtitles/the-wild-boys-esp.vtt",
      ciclo: "Teens",
      propuestaPor: "Mingo Morales",
    }
  ];

  return sutitlesObject;
};
